# Generated by Django 2.1.4 on 2019-01-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('productionYear', models.DateTimeField()),
                ('course', models.IntegerField()),
                ('engineCapacity', models.DecimalField(decimal_places=1, max_digits=2)),
                ('power', models.IntegerField()),
            ],
        ),
    ]
