# Generated by Django 2.1.4 on 2019-01-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GREEN', 'Green'), ('BROWN', 'Brown'), ('ORANGE', 'Orange')], default='WHITE', max_length=10),
        ),
    ]
