# Generated by Django 2.1.4 on 2019-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fuel',
            field=models.IntegerField(default=100),
        ),
    ]
