# Generated by Django 2.1.4 on 2019-01-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20190126_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
