# Generated by Django 2.1.4 on 2019-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AddField(
            model_name='car',
            name='carId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
