# Generated by Django 2.1.4 on 2019-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20190129_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carId',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offerId',
        ),
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='course',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
