# Generated by Django 2.1.4 on 2019-01-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_auto_20190129_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='productionYear',
            field=models.IntegerField(default=0),
        ),
    ]
