# Generated by Django 2.1.4 on 2019-02-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_auto_20190129_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
