# Generated by Django 2.1.4 on 2019-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_auto_20190205_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isReader',
            field=models.BooleanField(default=False),
        ),
    ]
