# Generated by Django 2.1.4 on 2019-02-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_message_isreader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isReader',
            new_name='isReaded',
        ),
    ]
