# Generated by Django 2.1.4 on 2019-02-05 21:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_auto_20190205_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='long',
        ),
    ]
