# Generated by Django 2.1.4 on 2019-02-05 22:04

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_auto_20190205_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
